services:
  db:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      RAILS_ENV: development
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "ruby ./bin/setup && bundle exec rails server -b 0.0.0.0"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      RAILS_ENV: development
    volumes:
      - ../:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
    