default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: voting_development

test:
  <<: *default
  database: voting_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
